"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['timetracker_app.py']
PACKAGES_NONZIP = ["/Volumes/karim/Desktop/Python Programming/site_packages/timetracker"]
PACKAGES = [] 
INCLUDES = []
RESOURCES = []
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    packages=PACKAGES,
    includes=INCLUDES,
    resources=RESOURCES,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

if PACKAGES_NONZIP:
    import shutil, os
    appname = APP[0].split(".")[0]
    for nonzip_package in PACKAGES_NONZIP:
        packagename = nonzip_package.split("/")[-1]
        nonzip_dir = "dist/%s.app/Contents/Resources/lib/python2.7/%s"%(appname,packagename)
        print nonzip_dir
        shutil.copytree(nonzip_package, nonzip_dir)
